version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drippingbasket.rule=Host(`thedrippingbasket.brich.one`)"
      - "traefik.http.routers.drippingbasket.entrypoints=https"
      - "traefik.http.routers.drippingbasket.tls=true"
      - "traefik.http.routers.drippingbasket.tls.certresolver=mytls"
      - "traefik.http.services.drippingbasket.loadbalancer.server.port=801"

networks:
  traefik:
    external: true
